export default {
    LOGIN: 'login',
    REGISTER: 'Register',
    FORGET: 'Forget password',
    VERIFY: 'verify',
    SPLASH: 'splash',
    APP_NAV: 'APP NAV',

    HOME_NAV: 'Home nav',
    HOME: 'Home',
    HOME_STACK: 'Home Stack',
    MY_GARDEN: 'My Garden',
    MY_PLANTS: 'My Plants',
    SETTINGS: 'Settings',
    ACCOUNT: 'Edit Account',
    ABOUT: 'About us',
    CAMERA: 'Camera',
    DETAILS: 'Details',
    HEALTH: 'Health',
    LIST: 'List Item',
    HOME_LIST: 'Home List',
    PROFILE: 'PROFILE',

    PLANTS_NAV: 'Plants Nav',
    GARDEN_NAV: 'Garden Nav',
    CAMERA_NAV: 'Camera Nav',

    ON_BOARDING_SCEEN: 'On Boardnig Screen',
    NEW_PASSWORD: 'New Password',
    NOTE_SCREEN: 'NOTES',
    CHOOSE_SCREEN: 'Choiser',
    PRE_CAMERA_SCREEN: 'Pre Camera screen',
    ACCOUNT_NAV: 'Account navigator',
    FIRST_RES: 'First result'
}